package com.TOTOMOFYP.VTOAPP.ui.outfits

/**
 * Data class representing an outfit
 */
data class Outfit(
    val id: String = "",
    val name: String = "", // User-provided outfit name
    val imageUrl: String = "",
    val date: String = "",
    val isFavorite: Boolean = false,
    val metadata: OutfitMetadata? = null, // Gemini-generated metadata
    val timestamp: String = "",
    val imageRes: Int = 0 // For backwards compatibility with resource images
)

/**
 * Metadata generated by Gemini AI for outfit
 */
data class OutfitMetadata(
    val description: String = "",
    val occasion: String = "",
    val color: String = "",
    val style: String = ""
) 